### ISSUE TITLE
Decide how to deal with searching key in parent contexts.

### ISSUE THREAD

**Issue by ylepikhov** [sviperll/static-mustache#3]
> <q>The most basic tag type is the variable. A {{name}} tag in a basic template will try to find the name key in the current context. If there is no name key, the parent contexts will be checked recursively. If the top context is reached and the name key is still not found, nothing will be rendered.</q><cite>
> [MUSTACHE(5)](http://mustache.github.io/mustache.5.html#Variables).
> </cite>

To do or not to do so.

**Comment by sviperll** [comment]
To do.

The decision is to follow mustache as close as possible. This is one of the premises of this project, Mustache proved to be practical enough to be popular.

In the case when we will try to reconsider mustache design. I still think that it is reasonable decision to reference parent contexts from child ones. This is called lexical scope. Lexical scope is used in majority of programming languages. Javascript is not javascript without lexical scope.

There are some problems with lexical scope. One of them is perceived ambiguity of reference in case where there are two variables with the same name, one in local context and another in parent context. Java explicitly forbids shadowing in the name of readability and clarity.
- We can't forbid shadowing in static-mustache since contexts are pla*in Java objects here and Java provides no restriction on field or method names.
- Contexts are pretty explicit and controllable in mustache and ambiguity is perception problem since disambiguation rules are really simple and familiar.
- In the case when you accidentally shadow parent's field you most likely get comile-time error since only limited number of types are renderable in static-mustache and references to non-renderable field is compile time error.
- dropping recursive lookup is not practival in mustache as it is. This will require lots of closing and reopening of contexts. The solution is to provide some new reference syntax, that is explicitly state the path from local context to referred field. My opinion is that introduced complexity is not worth provided benefits.
